---
all:
  children:
    minecraft:
      hosts:
        minecraft-server:
          ansible_host: "i-09e25c5c89636929e"
          ansible_user: ssm-user
          ansible_python_interpreter: /usr/bin/python3

          ansible_connection: aws_ssm
          ansible_aws_ssm_region: ap-northeast-1
          ansible_aws_ssm_bucket_name: "minecraft-prod-ssm-97e04346"
      vars:
        minecraft_version: "1.21.4"
        minecraft_memory: "2G"
        minecraft_port: 25565
        rcon_port: 25575