---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart minecraft
  community.docker.docker_compose_v2:
    project_src: "{{ minecraft_dir }}"
    state: present
    restarted: true